FROM node:20-alpine

WORKDIR /app

# Установка зависимостей для разработки
COPY package*.json ./
RUN npm install -d

# Установка netcat для проверки доступности PostgreSQL
RUN apk add --no-cache netcat-openbsd

# Копирование entrypoint скрипта
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3000

CMD ["npm", "run", "dev"]